host: localhost
port: 5000
logfile: /tmp/collector.log
loglevel: DEBUG

resources:
    - name: sample_resource
      secret: secret
      mongodb_host: localhost
      mongodb_port: 27017
      mongodb_db: sample_db
      mongodb_collection: collection
  
    - name: another
      secret: other_secret
      mongodb_host: localhost
      mongodb_port: 27017
      mongodb_db: russian
      mongodb_collection: vladimir
